### ISSUE TITLE
Add validator signed blocks consensus metrics

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/sl-exporter#11]
Currently, halflife checks how many of the last 20 blocks have been signed. 

We need something similar. Perhaps cosmos-exporter has some inspiration as well. 

We may want to configure the sign threshold given the different uptime parameters of blockchains. But, for example, if we fail to sign the last 100 blocks, that's indication of something wrong. 

See https://v1.cosmos.network/rpc/v0.41.4

Endpoint `GET /blocks/latest`

AFAICT, half-life polls a similar grpc endpoint. 

```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/sl-exporter/issues/41
- [ ] https://github.com/strangelove-ventures/sl-exporter/issues/37
- [x] latest_missed_blocks (use the signing info response)
```
